# This is a basic workflow to help you get started with Actions

name: Helm Chart

on:
  push:
    branches:
      - master
jobs:
  push-chart:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: 'helm plugin install https://github.com/chartmuseum/helm-push.git'
    - run: 'helm cm-push . https://charts.softonic.io -u ${{ secrets.HELM_REPO_USERNAME }} -p ${{ secrets.HELM_REPO_PASSWORD }}'
